## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file dining_philosophers.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (dining_philosophers.sagetex.sage) was *autogenerated* from dining_philosophers.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('dining_philosophers', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()

