## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file recycle.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (recycle.sagetex.sage) was *autogenerated* from recycle.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('recycle', version='2020/08/12 v3.5', version_check=True)

