## -*- encoding: utf-8 -*-
## This file (ldpc_ltc.sagetex.sage) was *autogenerated* from ldpc_ltc.tex with sagetex.sty version 2020/08/12 v3.5.
import sagetex
_st_ = sagetex.SageTeXProcessor('ldpc_ltc', version='2020/08/12 v3.5', version_check=True)
_st_.endofdoc()
