## -*- encoding: utf-8 -*-
## This file (graph-lifting.sagetex.sage) was *autogenerated* from graph-lifting.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('graph-lifting', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
