## -*- encoding: utf-8 -*-
## This file (synthesis.sagetex.sage) was *autogenerated* from synthesis.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('synthesis', version='2021/10/16 v3.6', version_check=True)
