## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file mthesis.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (mthesis.sagetex.sage) was *autogenerated* from mthesis.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('mthesis', version='2021/10/16 v3.6', version_check=True)

