## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file presentation.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_149 = Integer(149); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)## This file (presentation.sagetex.sage) was *autogenerated* from presentation.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('presentation', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_149 
_st_.blockbegin()
try:
except:
 _st_.goboom(_sage_const_149 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_149 
 _st_.inline(_sage_const_0 , graphs_tex)
except:
 _st_.goboom(_sage_const_149 )
try:
 _st_.current_tex_line = _sage_const_149 
 _st_.inline(_sage_const_1 , graphs_tex_2)
except:
 _st_.goboom(_sage_const_149 )
_st_.endofdoc()

